image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - test
  - deploy


pytest_cov:
  stage: test
  tags:
    - docker
  script:
    - pip install pytest pytest-cov
    - pip install -e .
    - pytest --cov=. --cov-report xml src/tests
    - coverage report --include="src/{{cookiecutter.project_name}}/**.py"
    - coverage html --include="src/{{cookiecutter.project_name}}/**.py"
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - htmlcov
  coverage: '/^TOTAL.+?(\d+\%)$/'


pages:
  stage: deploy
  tags:
    - docker
  script:
    - pip install sphinx
    - cd doc
    - sphinx-build source build
    - mv build ../public
    - mv ../htmlcov ../public/.
  artifacts:
    paths:
      - public
  only:
    - master


to_pypi:
  stage: deploy
  tags:
    - docker
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=__token__ twine upload dist/*
  when: manual
  only:
    - master