image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
  tags:
    - docker

stages:
  - test
  - deploy

style:
  stage: test
  script:
    - pip install . pre-commit
    - pre-commit run --all-files

pytest_cov:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pip install -e .
    - pytest --cov=. --cov-report xml src/tests
    - coverage report --include="src/{{cookiecutter.project_name}}/**.py"
    - coverage html --include="src/{{cookiecutter.project_name}}/**.py"
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - htmlcov
  coverage: '/^TOTAL.+?(\d+\%)$/'


py3{{cookiecutter.minimum_python_version}}:
  image: python:3.{{cookiecutter.minimum_python_version}}
  stage: test
  script:
    - pip install pytest
    - pip install -e .
    - pytest src/tests


pages:
  stage: deploy
  script:
    - pip install . sphinx myst-parser
    - cd doc
    - sphinx-build source build
    - mv build ../public
    - mv ../htmlcov ../public/.
  artifacts:
    paths:
      - public
  only:
    - main


to_pypi:
  stage: deploy
  script:
    - pip install twine build
    - python -m build
    - twine check dist/*
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=__token__ twine upload dist/* --verbose
  when: manual
  only:
    - main
