[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

# linting
[flake8]
max-line-length = 99
ignore = "E203,E501,W503"

[darglint]
strictness="long"

[tool.isort]
profile = "black"
